version: '3'

services:
  next-app:
    container_name: next-app
    build:
      context: ./next-app
      dockerfile: prod.Dockerfile
      args:
        NEXT_PUBLIC_NEXTAUTH_URL: ${NEXT_PUBLIC_NEXTAUTH_URL}
        NEXT_PUBLIC_USERNAME: ${NEXT_PUBLIC_USERNAME}
        NEXT_PUBLIC_PASSWORD: ${NEXT_PUBLIC_PASSWORD}
        NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
        NEXT_PUBLIC_API_RETRY_INTERVAL_IN_SECONDS: ${NEXT_PUBLIC_API_RETRY_INTERVAL_IN_SECONDS}
        NEXT_PUBLIC_API_MAX_RETRY: ${NEXT_PUBLIC_API_MAX_RETRY}
        NEXT_PUBLIC_DHCP_CONF_FILE_PATH: ${NEXT_PUBLIC_DHCP_CONF_FILE_PATH}
        NEXT_PUBLIC_DHCP_LEASE_FILE_PATH: ${NEXT_PUBLIC_DHCP_LEASE_FILE_PATH}
        NEXT_PUBLIC_DHCP_LOG_FILE_PATH: ${NEXT_PUBLIC_DHCP_LOG_FILE_PATH}
        NEXT_PUBLIC_API_TZ: ${NEXT_PUBLIC_API_TZ}
        NEXT_PUBLIC_API_LOCALE: ${NEXT_PUBLIC_API_LOCALE}
    volumes:
      - type: bind
        source: /etc/dhcp/
        target: /app/dhcp/conf/
      - type: bind
        source: /var/lib/dhcpd/
        target: /app/dhcp/leases/
      - type: bind
        source: /var/log/
        target: /app/dhcp/log/
    restart: always
    ports:
      - 3000:3000
    networks:
      - dhcp-monitan_network

  # Add more containers below (nginx, postgres, etc.)

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  dhcp-monitan_network:
    external: true
